package cn.com.sky.algorithms.leetcode.easy;

import org.junit.Test;

/**
 * <pre>
 * 
 * 389. Find the Difference
 * 
 * Given two strings s and t which consist of only lowercase letters.
 * 
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * 
 * Find the letter that was added in t.
 * 
 * Example:
 * 
 * Input:
 * s = "abcd"
 * t = "abcde"
 * 
 * Output:
 * e
 * 
 * Explanation:
 * 'e' is the letter that was added.
 * 
 * 
 * </pre>
 */
public class FindtheDifference389 {

	@Test
	public void solution() {
		String s = "ab+cd";
		String t = "ab+cd-";

		char c = findTheDifference(s, t);
		System.out.println(c);
	}

	public char findTheDifference(String s, String t) {

		String result = s.concat(t);
		char arr[] = result.toCharArray();
		int c = 0;
		for (int i = 0; i < arr.length; i++) {
			c ^= arr[i];
		}

		return (char) c;

	}
}
